[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"
  publish = "public/dist"  # Adjust this based on your output directory
  environment = { NODE_VERSION = "14.x" }

